### ISSUE TITLE
Add gf_scales()

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#1]
Have to think a bit about the API for this if we want to avoid having a function for each of the many scales functions in `ggplot2`.

**Comment by dtkaplan** [comment]
A proposal ...

Here's a working implementation of one possibility: have one catch-all that can be used for any `scale_` or `theme_` in `ggplot2`, e.g.
```{r}
gf_refine <- function(plot = NULL, ...) {
  if ( ! inherits(plot, "ggplot")) {
    warning("gf_refine() needs a plot piped as a first argument.")
  } else {
    gg_refinements <- list(...)
    for (x in gg_refinements)  plot <- plot + x
  }
  
  plot
}
```

To be used like this:
```{r}
gf_point(mpg ~ hp, data = mtcars) %>% 
  gf_refine(xlim(0,400), ylim(0,50), scale_x_log10())
```

I think it might be nice to have special forms for the most commonly used refinements, provide a `gf_` function, e.g.
```{r}
gf_limits <- function(placeholder = NULL, x = NULL, y = NULL) { 
# Call xlim(), ylim() as appropriate and add them to the placeholder in the output
}
gf_labels <- function(placeholder=NULL, x=NULL, y = NULL, title = NULL, subtitle = NULL){
# similar to the above
}
```

**Comment by rpruim** [comment]
`gf_lims()`, `gf_labs()`, and `gf_theme()` already exist.  They are easy, they just wrap calls to `lims()`, `labs()`, and `theme()` and pass along their arguments.

`gf_refine()` would be pretty easy as well.  But it means you still need to know how the underlying `ggplot2` functions work to use it, and they aren't as natural as `lims()`, `labs()`, and `theme()` (because the do a more complex task).

I can certainly add `gf_refine()`.  And we can continue to think about how we might like `gf_scales()` to behave.

**Comment by rpruim** [comment]
Works like a charm:
```
p <- gf_point(length ~ width + color:sex, data = KidsFeet) 
p %>% gf_refine(scale_color_manual(values = c(B = "blue", G = "green")))
```
And it's a one-liner:
```r
gf_refine <- function(object, ...) {
  Reduce(`+`, list(...), init = object)
}
```

**Comment by rpruim** [comment]
I'm moving the last comment to its own issues.

**Comment by rpruim** [comment]
Since `gf_refine()` is working and there has been no subsequent demand for somethings tailored directly at scales, I'm going to close this.
