### ISSUE TITLE
Add support for ggstance?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#103]
Among other things, this would provide "natural" horizontal versions of geoms and stats (e.g. boxplot) that would not require the use of `coord_flip()`.

This could be added in `ggformula`, or it could be put into `ggformulaExtra`.

See https://cran.r-project.org/web/packages/ggstance/README.html

**Comment by lionel-** [comment]
I will send an update to CRAN soon for 3.0 compatibility.

**Comment by rpruim** [comment]
@lionel- , thanks for the update.  Any idea how soon soon might be?  If it is very soon, I'll likely delay submission for `ggfomula` until this is in place.  If it is still a couple weeks off, I'll plan to catch this in the next round.
