### ISSUE TITLE
`gf_counts` with an integer variable uses decimals on x-scale

### ISSUE THREAD

**Issue by lahvak** [ProjectMOSAIC/ggformula#111]
When creating a bar chart of a discrete numerical variable using `gf_count`, the scale on the x-axis has ticks and labels at decimal values, even though the values of the variable are all integers.  

I understand that in many cases, integer values actually represent a continuous variable.  In such cases, though, it would in my opinion make little sense to use a count based bar chart to display the data: a histogram with bin width of 1 would be more proper.  I believe that a bar chart should by default have a discrete scale on the x-axis.

It is of course possible to convert the integer variable to a factor, specifying levels as min:max of the variable and set `drop = FALSE` for the discrete x-scale, it is however a lot of work to get a result that should be the default.  The `ggformula` package is often used in introductory statistics courses, and my experience is that the current behavior is confusing for students in such courses.

**Comment by rpruim** [comment]
Finally getting back to this.  You didn't provide an example, so I tried creating one, and the only instance I came up with quickly was when the data consisted of two consecutive integers.  Are you seeing this more often?

Another option for this sort of plot is to use a histogram with `binwidth = 1`.  That's my usual way of plotting integer data.

``` r
library(ggformula)
gf_histogram(~ rbinom(100, 15, 0.4), binwidth = 1)
```

![](https://i.imgur.com/K7CfOoO.png)

<sup>Created on 2019-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rpruim** [comment]
Before closing this, I decided to add a little function that can assist in setting the breaks used for a plot.  Currently the name is `discrete_breaks()`.  A resolution can be set to give breaks that are multiples of the resolution and roughly spanning the range of the data.  The default resolution is 1, which provides breaks at each integer.

``` r
suppressPackageStartupMessages(library(ggformula))
x <- rbinom(100, 100, 0.4)
p <- gf_bar( ~ x)
p %>% gf_refine(scale_x_continuous(breaks = discrete_breaks()))
```

![](https://i.imgur.com/ZdZF7x9.png)

``` r
p %>% gf_refine(scale_x_continuous(breaks = discrete_breaks(5)))
```

![](https://i.imgur.com/GSJP0a5.png)

``` r
p %>% gf_refine(scale_x_continuous(breaks = discrete_breaks(2)))
```

![](https://i.imgur.com/nc9bhVD.png)

<sup>Created on 2019-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
