### ISSUE TITLE
Cannot run ggformula tutorials (learnr) from within rstudio.cloud

### ISSUE THREAD

**Issue by lbcollins** [ProjectMOSAIC/ggformula#115]
Short version: `ggformula` tutorials do not work via `learnr` from within rstudio.cloud.

When logged in at rstudio.cloud (with `learnr` and `ggformula` packages and their dependencies installed), typing `learnr::run_tutorial("introduction", package = "ggformula")` in the _Console_ results in a new browser window opening, but the browser just displays this text error message: `ERROR: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'bootstrap-3.3.5'; `directoryPath` = ' '`.

I may be asking too much to expect `learnr` tutorials to work from within rstudio.cloud and this is likely an rstudio.cloud issue, not a `learnr` nor `ggformula` issue, but I thought I would start with the `ggformula` folks to see if you had any thoughts.

**Comment by rpruim** [comment]
Thanks for the heads up.  I haven't used rstudio.cloud for several months, but I may be using it for a workshop in a couple weeks, so I'd also like this to work.

Have you tried any tutorials from other packages to see if they work?

**Comment by lbcollins** [comment]
I made an example learnr tutorial .Rmd file (below) and it does run from within rstudio.cloud perfectly (clicking on "Run Document") .  So, you *can* run learnr tutorials within rstudio.cloud.  

Now, I'll search for a tutorial from another package and see if that works from within rstudio.cloud.  I'll write back again shortly.

---
title: "learnr tutorial"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

Add two plus two

```{r addition, exercise = TRUE}
1 + 2
```

**Comment by lbcollins** [comment]
This does **NOT** appear to be a ggformula package issue.  I get the same error on rstudio.cloud when running `learnr::run_tutorial("hello", package="learnr")` in the Console.  I will go to the RStudio Community forum to ask my question.  Thank you for your time.

**Comment by nicholasjhorton** [comment]
Linda, I’d be interested in hearing what response you get from the RStudio Community forum.

Thanks and best wishes for the New Year,

Nick

Nicholas Horton 
Beitzel Professor of Technology and Society (Statistics and Data Science)
Amherst College


On Jan 1, 2019, at 4:18 PM, Linda Collins <notifications@github.com> wrote:

This does NOT appear to be a ggformula package issue. I get the same error on rstudio.cloud when running learnr::run_tutorial("hello", package="learnr") in the Console. I will go to the RStudio Community forum to ask my question. Thank you for your time.

**Comment by lbcollins** [comment]
Hi, Nick.

I put a new, related ProjectMOSAIC/ggformula post on GitHub: https://github.com/ProjectMOSAIC/ggformula/issues/116#issue-395113686

...and here is my relevant post to the RStudio Community: https://community.rstudio.com/t/learnr-run-tutorial-not-working-on-rstudio-cloud/20674?u=lbcollins

Linda



On Jan 2, 2019, at 9:15 AM, Nicholas Horton <notifications@github.com<mailto:notifications@github.com>> wrote:

Linda, I’d be interested in hearing what response you get from the RStudio Community forum.

Thanks and best wishes for the New Year,

Nick

Nicholas Horton
Beitzel Professor of Technology and Society (Statistics and Data Science)
Amherst College


On Jan 1, 2019, at 4:18 PM, Linda Collins <notifications@github.com<mailto:notifications@github.com>> wrote:

This does NOT appear to be a ggformula package issue. I get the same error on rstudio.cloud when running learnr::run_tutorial("hello", package="learnr") in the Console. I will go to the RStudio Community forum to ask my question. Thank you for your time.
