### ISSUE TITLE
Would you consider hosting your ggformula tutorials on a shiny server?

### ISSUE THREAD

**Issue by lbcollins** [ProjectMOSAIC/ggformula#116]
This would alleviate a current issue where `learnr::run_tutorial("tutorial_name", package = "package_name")` does not work on rstudio.cloud.

I have written to the RStudio Community about the rstudio.cloud issue.

**Comment by lbcollins** [comment]
My RStudio Community post is here: https://community.rstudio.com/t/learnr-run-tutorial-not-working-on-rstudio-cloud/20674?u=lbcollins

No answers yet as of Wed, Jan 2, 10:30am CST

**Comment by rpruim** [comment]
I just tried running the tutorial in rstudio.cloud and it appears to still not be possible to do this.  As I get ready for the next CRAN release, I'll consider posting the tutorials on a public server.

**Comment by rpruim** [comment]
At least temporarily this is now available.  I'll have to see how much load it generates.  If our server gets swamped, I'll pull it down.

It is not intended to support large numbers of simultaneous tutorial users.
