### ISSUE TITLE
When evaluating params = list(param1 = foo, param2 = bar), gf_dist() is influenced by the "wrong" environment

### ISSUE THREAD

**Issue by homerhanumat** [ProjectMOSAIC/ggformula#119]
This works fine:

```
library(ggformula)
f1 <- function(a, b) {
  p <- gf_dist("gamma", shape = a, rate = b)
  print(p)
}
f1(a = 3, b = 10)
```

But this:

```
f2 <- function(a, b) {
  p <- gf_dist("gamma", params = list(shape = a, rate = b))
  print(p)
}
f2(a = 3, b = 10)
```

throws error:

```
Error in (function (object = NULL, gformula = NULL, data = NULL, alpha,  : 
  object 'a' not found
```

But now add a couple of items to the Global Environment

```
a <- "hello"
b <- "there!"
```

Then the following call produces the expected graph:

```
f2(a = 100, b = 1)
```

Remove an item:

```
rm(a)
```

Then `f2(a = 100, b = 1)` throws the error again.

The problem seems to occur at lines 197-201 in `gf_dist.R`, in:

```
do.call(
               gf_line,
               c(list(object, rlang::set_env(density ~ x, parent.frame()),
                      data = data.frame(density = ydata, x = fewer_values)),
              dots)),
```

At this point value of `dots` is a list with one item named `params`, the value being the call `list(shape = a, rate = b)`.  Since by this time `a` and `b` have already been used to obtain the `x` and `ydata` values, the error is avoided in the above examples simply by not including `dots` in the `do.call()` list.  As it stands the call `list(shape = a, rate = b)` gets passed to some helper function where it is evaluated (spuriously) in a setting where the search path does not include the run-time environment of `geom_dist()`.

Maybe prior to this and related calls have something like the following?

```
if (!is.null(dots$params) {
  dots$params <- NULL
}
```

Or something more general that removes all potentially problematic elements from `dots`?

**Comment by rpruim** [comment]
This may likely need to wait until summer.  When the new ggplot2 was released, it handled evaluation very differently, and I didn't have time and the time to delve into all the details to figure out the best ways to get things evaluated where I want them evaluated.  (The main question is how to tell ggplot2 where to look.)

Another similar issue is when you have a variable and a function with the same name -- ggplot2 ends up grabbing the one you don't want and throwing an error:

``` r
library(ggformula)
t <- 5; u <- 5
gf_hline(yintercept =   t)  # works if we *set* the value, but if we *map*...
```

![](https://i.imgur.com/IVra2np.png)

``` r
gf_hline(yintercept = ~ t)  # ack: grabbing base::t() instead of one in global environment
#> Don't know how to automatically pick scale for object of type function. Defaulting to continuous.
#> Error: All columns in a tibble must be 1d or 2d objects:
#> * Column `yintercept` is function
gf_hline(yintercept = ~ u)  # no function named u(), so it works as desired.
```

![](https://i.imgur.com/onecsR9.png)

<sup>Created on 2019-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The safest solution is always have values in a data frame (at least for now).

**Comment by rpruim** [comment]
See also #110 and #96.

**Comment by rpruim** [comment]
This is fixed now in the beta branch.  Coming to a CRAN mirror near you at the next release.

``` r
suppressPackageStartupMessages(library(ggformula))
f2 <- function(a, b) {
  p <- gf_dist("gamma", params = list(shape = a, rate = b))
  print(p)
}
f2(a = 3, b = 10)
```

![](https://i.imgur.com/jzeVV4d.png)

<sup>Created on 2019-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The problem was due to retaining `params` in a list where it didn't need to be after its information was extracted (in the correct environment) earlier.
