### ISSUE TITLE
gf_histogram in percent

### ISSUE THREAD

**Issue by EricSHo** [ProjectMOSAIC/ggformula#121]
Hi,

A basic question: is there a way to make a gf_histogram where the y-axis shows percent?

Thanks, Eric.

**Comment by rpruim** [comment]
Here's one way:

``` r
suppressPackageStartupMessages(library(ggformula))
theme_set(theme_bw())
gf_histogram(stat(count/sum(count)) ~ Sepal.Length, data = iris) %>%
  gf_labs(y = "") %>%
  gf_refine(scale_y_continuous(labels = scales::percent))
```

![](https://i.imgur.com/Vde3eiH.png)

<sup>Created on 2019-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rpruim** [comment]
@EricSHo sorry for the long delay.  Your issue came during the semester crunch time.
