### ISSUE TITLE
gf_factory exported? add gf_sina() to ggformula?

### ISSUE THREAD

**Issue by lebebr01** [ProjectMOSAIC/ggformula#134]
@rpruim This may be related to a point raised in issue #29 , where I can't find the function, `gf_factory()`. I'm trying to create a new function, `gf_sina()` using `geom_sina()` from the ggforce package: [sina plots](https://ggforce.data-imaginist.com/reference/geom_sina.html). With @zief0002 we are creating some materials for an intro stat audience and would like to have sina plots over violin plots.

I believe I created a similar structure in my forked repo to mimic code from the ggstance.R file, [my attempt at gf_sina](https://github.com/lebebr01/ggformula/blob/ggforce/R/ggforce.R). I get the following error: 

A few questions:
1. Would you be interested in including this functionality into ggformula?
2. Is it currently possible for others to add new `gf_*` functions?
3. Would you be interested in a PR for this functionality?

Thanks in advance for your assistance.

**Comment by rpruim** [comment]
Hmm.. I thought I had posted a response to this long ago.  I must have been interrupted before submitting the comment.  My apologies for the long delayed answer.

ggformula does export `layer_factory()`, and it can be used to create new `gf_` functions.

``` r
library(ggforce)
#> Loading required package: ggplot2
library(ggformula)
#> Loading required package: ggstance
#> 
#> Attaching package: 'ggstance'
#> The following objects are masked from 'package:ggplot2':
#> 
#>     geom_errorbarh, GeomErrorbarh
#> 
#> New to ggformula?  Try the tutorials: 
#>  learnr::run_tutorial("introduction", package = "ggformula")
#>  learnr::run_tutorial("refining", package = "ggformula")
gf_sina <- layer_factory(geom  = "point", stat = "sina")
gf_sina(age ~ substance, data = mosaicData::HELPrct)
```

![](https://i.imgur.com/rehGKXP.png)

<sup>Created on 2020-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rpruim** [comment]
I'll be submitting a new version of ggformula to CRAN soon.  I could perhaps add `gf_sina()` in that release.

**Comment by dtkaplan** [comment]
Yes, do.  The people at my JMM workshop suggested a plot like this.

- Danny

**Comment by lebebr01** [comment]
Thank you, I appreciate your time on this!

**Comment by rpruim** [comment]
done.  Well at least the code part.  Need to check documentation and add tests.

``` r
library(ggformula)
#> Loading required package: ggplot2
#> Loading required package: ggstance
#> 
#> Attaching package: 'ggstance'
#> The following objects are masked from 'package:ggplot2':
#> 
#>     geom_errorbarh, GeomErrorbarh
#> 
#> New to ggformula?  Try the tutorials: 
#>  learnr::run_tutorial("introduction", package = "ggformula")
#>  learnr::run_tutorial("refining", package = "ggformula")
example(gf_sina)
#> 
#> gf_sin> gf_sina(age ~ substance, data = mosaicData::HELPrct)
```

![](https://i.imgur.com/CCihscb.png)

<sup>Created on 2020-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rpruim** [comment]
I'm adding an example use of `gg_sina()` (overlaid on a violin plot) to ggformula.Rmd.

``` r
library(ggformula)
#> Loading required package: ggplot2
#> Loading required package: ggstance
#> 
#> Attaching package: 'ggstance'
#> The following objects are masked from 'package:ggplot2':
#> 
#>     geom_errorbarh, GeomErrorbarh
#> 
#> New to ggformula?  Try the tutorials: 
#>  learnr::run_tutorial("introduction", package = "ggformula")
#>  learnr::run_tutorial("refining", package = "ggformula")
theme_set(theme_bw())
gf_violin(age ~ substance, data = mosaicData::HELPrct) %>%
    gf_sina(alpha = 0.3)
```

![](https://i.imgur.com/Kz71kgM.png)

<sup>Created on 2020-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
