### ISSUE TITLE
gf_lm extended to group models

### ISSUE THREAD

**Issue by jiyunson** [ProjectMOSAIC/ggformula#138]
We teach intro stats completely as modeling and we really like how gf_lm() makes it easy for our students to add the linear model to a plot like this:

```
gf_point(Sepal.Length ~ Sepal.Width, data=iris)%>%
gf_lm()
```
![image](https://user-images.githubusercontent.com/30084828/74874911-5180c180-5316-11ea-8b15-24dd6090ce16.png)

We wish that something as elegant could be done with a simple model of categorical data such as:
```
gf_jitter(Sepal.Length ~ Species, data=iris)%>%
gf_lm()
```
Currently we use hacks like these:
```
model1 <- lm(Sepal.Length ~ Species, data = iris)
gf_jitter(Sepal.Length ~ Species, data=iris, width = .2)%>%
gf_jitter(predict(model1) ~ Species, data = iris, color = "blue", height=0, width = .2)
```
![image](https://user-images.githubusercontent.com/30084828/74875233-c653fb80-5316-11ea-84ef-7d5426d5c64f.png)

Or like this:
```
sepal.stats <- favstats(Sepal.Length ~ Species, data = iris)
gf_jitter(Sepal.Length ~ Species, data=iris, width = .2)%>%
gf_errorbar(mean + mean ~ Species, data = sepal.stats, color = "blue")
```
![image](https://user-images.githubusercontent.com/30084828/74875564-55f9aa00-5317-11ea-93ca-4b53911048eb.png)

**Comment by rpruim** [comment]
I don't think extending `gf_lm()` is the right solution.  It is intended to be a wrapper around `geom_lm()` and should match the behavior of that geom.  (If that geom were updated, things in ggformula should be updated automatically.)

The problem here is that there isn't a fantastic way to do this in ggplot2 because there isn't (as far as I know) a geom that creates horizontal line segments like one piece of an errorbar.  There is no reason why such a geom couldn't be created, however.

In the meantime, here are two alternatives.  The first is easy, but it doesn't give you the plot you want.  The second is similar to your errorbar approach but avoids the need to create an auxiliary data set explicitly since `stat_summary()` does it for us.

``` r
suppressPackageStartupMessages(library(ggformula))
suppressPackageStartupMessages(library(mosaic))
gf_jitter(Sepal.Length ~ Species, data=iris, width = .2 )  %>%
  gf_point(stat = "summary", color = "red")
#> No summary function supplied, defaulting to `mean_se()`
```

![](https://i.imgur.com/FTKCNLg.png)

``` r
gf_jitter(Sepal.Length ~ Species, data=iris, width = .2 ) %>%
  gf_errorbar(stat = "summary", color = "red", width = 0.5,
              fun.max = mean, fun.min = mean) 
```

![](https://i.imgur.com/lB4K47O.png)

``` r

mean3 <- function(x) { 
  data.frame(ymin = mean(x), ymax = mean(x), y = mean(x))
}
gf_jitter(Sepal.Length ~ Species, data=iris, width = .2 ) %>%
  gf_errorbar(stat = "summary", color = "red", fun.data = mean3, width = 0.5)
```

![](https://i.imgur.com/p9nGuUv.png)

<sup>Created on 2020-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jiyunson** [comment]
Thanks for considering! This has been a great additional option for our students.

gf_jitter(Sepal.Length ~ Species, data=iris, width = .2 )  %>%
  gf_point(stat = "summary", color = "red")

**Comment by rpruim** [comment]
@jiyunson , after a long pause, I'm back at this issue.  As I mentioned before, it would be possible to create a new geom to make this easier.  Actually, I've created three, one each for adding horizontal bars, vertical bars, or both (a plus).  Still considering whether hbar and vbar are the best names for these. 

hbar and vbar currently use `stat = 'summary'` for their default, so they add a bar at the mean (or some other statistic, which you can set using `fun = `).

Here are some examples.  Let me know what you think.

``` r
suppressPackageStartupMessages(library(ggformula))
gf_hbar(length ~ sex, data = mosaicData::KidsFeet, width = 0.1) |> 
  gf_jitter(width = 0.1)
#> No summary function supplied, defaulting to `mean_se()`
```

![](https://i.imgur.com/GvllTwF.png)

``` r
gf_hbar(length ~ sex, data = mosaicData::KidsFeet, width = 0.1, fun = max) |> 
  gf_jitter(width = 0.1)
```

![](https://i.imgur.com/lq4Q4e6.png)

``` r
gf_hbar(length ~ sex, data = mosaicData::KidsFeet, width = 0.1, stat = "identity") |> 
  gf_jitter(width = 0.1)
```

![](https://i.imgur.com/OuHzogV.png)

``` r
gf_plus(length ~ sex, data = mosaicData::KidsFeet, width = 0.02, height = 0.1, size = 0.4)
```

![](https://i.imgur.com/0YZN1fM.png)

<sup>Created on 2022-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jiyunson** [comment]
Ah these are fun!

Our team (specifically Adam Blake) is working on a function that will be able to put a model (from `lm()`). We want our students to see that all these models have a basic similarity (i.e., represented in GLM notation) so we're calling it `gf_model()` that we can layer onto a graph (e.g., `gf_jitter(Y ~ X, data = df) %>% gf_model(lm(Y ~ X, data = df))`).

https://github.com/UCLATALL/coursekata-r
