### ISSUE TITLE
Allow users to control "denominators" used in gf_props()

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#139]
This supersedes #112, I think.

Ideas:

* default to computing proportions separately in each panel
* provide a `denom` argument that allows for other choices

Current WIP implementation uses `ggplot2::after_stat()` and so can determine the denominator based on anything computable from the statified data.

Here are some examples.

``` r
suppressPackageStartupMessages(library(mosaic))
theme_set(theme_bw())

T <- dplyr::bind_rows(
  do(20) * tibble(a = "A", b = "E", c = "X"),
  do(20) * tibble(a = "A", b = "E", c = "Z"),
  do(10) * tibble(a = "A", b = "F", c = "X"),
  do(10) * tibble(a = "A", b = "F", c = "Z"),
  do(5)  * tibble(a = "B", b = "E", c = "X"),
  do(10) * tibble(a = "B", b = "E", c = "Z"),
  do(15) * tibble(a = "B", b = "F", c = "X"),
  do(10) * tibble(a = "B", b = "F", c = "Z"),
)  

T %>% gf_props( ~ a | b ~ c, position = "dodge", 
                title = "proportions within panel")
```

![](https://i.imgur.com/ZmjsgT6.png)

``` r
T %>% gf_props( ~ a | b ~ c, fill = ~ b, position = "dodge", denom = ~ fill,
                title = "proportions within fill") 
```

![](https://i.imgur.com/UDfqoDf.png)

``` r
T %>% gf_props( ~ a | b ~ c, fill = ~ c, position = "dodge", denom = ~ fill,
                title = "proportions within fill")
```

![](https://i.imgur.com/s0B12YI.png)

``` r
T %>% gf_props( ~ a | b, fill = ~ c, position = "dodge", denom = ~ 1,
                title = "proportions within all")
```

![](https://i.imgur.com/o1wwUJf.png)

``` r
T %>% gf_props( ~ a | b ~ c, fill = ~ b, denom = ~ fill,
                title = "proportions within fill")
```

![](https://i.imgur.com/UkGBfiQ.png)

``` r
T %>% gf_props( ~ a | b ~ c, fill = ~ c, group = ~b, denom = ~ fill,
                title = "proportions within fill")
```

![](https://i.imgur.com/XpOYUoX.png)

``` r
T %>% gf_props( ~ a | b ~ c, fill = ~ c, group = ~b, denom = ~ group,
                title = "proportions in group (b = E or F)")
```

![](https://i.imgur.com/AUtkAol.png)

<sup>Created on 2020-07-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rpruim** [comment]
To do:

* [ ] Tests
* [ ] Documentation
* [ ] Examples
* [ ] Decide if there are any important use cases this doesn't handle.

**Comment by rpruim** [comment]
@dtkaplan and @nicholasjhorton : Have either of you used this feature?  Any comments?

**Comment by nicholasjhorton** [comment]
I've not used this feature.
