### ISSUE TITLE
vignette update?

### ISSUE THREAD

**Issue by bhaney22** [ProjectMOSAIC/ggformula#142]
https://www.rdocumentation.org/packages/ggformula/versions/0.9.4/vignettes/ggformula.Rmd

When I run the scripts in this vignette, they do not run because they do not find the gf_...() commands. I have to manually add the "library(ggformula)"  to every script.

**Comment by rpruim** [comment]
We don't control that page, so you would need to contact the people who do to get that page working the way you would like.  In the actual vignette, package loading happens in a set up chunk and all packages are available thereafter.  Also, code run in earlier chunks affects the behavior of subsequent chunks.

If you want to view the vignette, I recommend viewing it https://projectmosaic.github.io/ggformula/articles/ggformula.html.  You should also be able to view the vignette from within R/RStudio.
