### ISSUE TITLE
Consider redoing using "labelled" data labels in plots.

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#148]
Issues with current implementation:

1. A new package ({declared}) exists, and we should check that things work with that package.
2. Labeling is currently handled by `print()`, so it doesn't play well with {patchwork}.
3. We currently use the label attribute.  Need to decide if this is too flexible.  {broom} for example, labels residuals based on the original variable name if that variable had a label -- need to see if {broom} considers this a bug or a feature.  (See #146)

**Comment by rpruim** [comment]
We can monitor https://github.com/tidymodels/broom/issues/1031 to see if {broom} considers its behavior to be a bug or a feature.

**Comment by rpruim** [comment]
Regarding 1: It appears that things work out-of-the box with {declared}.

So we need to wait to hear about 3 and decide how much effort to put into 2.  If {broom} considers the current behavior to be desirable, there may not be much we can do about this -- there is no way for us to tell how the labels came to be, and I think we want to use variable labels when they exist.

I guess we could add an additional argument to let users select whether to use labels or not.  Implementation may depend on how we deal with item 2.

**Comment by nicholasjhorton** [comment]
This is feeling very complicated.  I don't have strong feelings but suspect that for me I'll encourage my students to use `gf_labs()`.

**Comment by rpruim** [comment]
After a bit of discussion, {broom} decided number 3 above wasn't their problem either.  So I've posted an issue with {labelled}. (https://github.com/larmarange/labelled/issues/102).  The issue is that when doing arithmetic with labelled vectors, the labels stick, even though they probably should not.  If {labelled} and {declared} would fix this, that would take care of our problems.

**Comment by rpruim** [comment]
@nicholasjhorton , the advantages of using labels are 

1. Support for data imported from SPSS.
2. Consistency across multiple plots using the same data.
3. Avoidance of errors: It is easy to change a variable and forget to change the labeling.
4. DRY: No need to use `gf_labs()` with every plot, just add the labels once.
5. If you use the list features of set_variable_labels(), you can easily set consistent names across multiple data sets.

This actually arose when a colleague migrating from SPSS asked me about support for this sort of thing.  So I'd like to support it for those who want to take advantage, but I'd like to take care of some of the rough edges if I'm able to do so relatively easily.

**Comment by rpruim** [comment]
Status report: The use of `gf_relabel()` allows the user to create plots using labels stored in the data (as per the packages listed above) or to supply a list of labels to be assigned to each variable.  This is called by default when a ggformula plot is printed (looking for labels stored with the data).  But it can be called explicitly, and needs to be to play correctly with something like {patchwork}, which doesn't call the print method.  This seems like a sufficient method for the moment.

``` r
suppressPackageStartupMessages(library(ggformula))

gf_point( cesd ~ age, data = mosaicData::HELPrct)
```

![](https://i.imgur.com/Y12YUDJ.png)

``` r

suppressPackageStartupMessages(library(patchwork))

gf_point( cesd ~ age, data = mosaicData::HELPrct) |
gf_point( cesd ~ age, data = mosaicData::HELPrct)
```

![](https://i.imgur.com/yHwvOZa.png)

``` r


gf_point( cesd ~ age, data = mosaicData::HELPrct) |>
  gf_relabel() |
gf_point( cesd ~ age, data = mosaicData::HELPrct)
```

![](https://i.imgur.com/AWCfTih.png)

``` r


palmerpenguins::penguins |>
  gf_point(bill_length_mm ~ flipper_length_mm, color = ~ species, shape = ~ island) 
#> Warning: Removed 2 rows containing missing values (geom_point).
```

![](https://i.imgur.com/CCGxZNA.png)

``` r


penguin_labels <- 
  list(
    species = "Species",
    island = "Island",
    bill_length_mm = "bill length (mm)", 
    flipper_length_mm = "flipper length (mm)"
  )
palmerpenguins::penguins |>
  gf_point(bill_length_mm ~ flipper_length_mm, color = ~ species, shape = ~ island) |>
  gf_relabel(penguin_labels)
#> Warning: Removed 2 rows containing missing values (geom_point).
```

![](https://i.imgur.com/ILuzBwk.png)

<sup>Created on 2022-08-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
