### ISSUE TITLE
Properly reexporting functions from `labelled`

### ISSUE THREAD

**Issue by larmarange** [ProjectMOSAIC/ggformula#160]
Hi

I'm preparing a new release of the `labelled` package. https://github.com/larmarange/labelled/issues/139

The function `var_label()` is introducing new arguments. As this function is copied rather than reexported in `ggformula`, it is creating inconsistency in the documentation, resulting in a warning when performing rev dep checks, cf. https://github.com/larmarange/labelled/blob/main/revdep/problems.md

To avoid any issue with evolutions of `labelled`, it would be better to reexports properly the different functions, as proposed in https://github.com/ProjectMOSAIC/ggformula/pull/159 

Could you consider merging this pull request and releasing a new version of your package to avoid any problem on CRAN?

Best regards

**Comment by larmarange** [comment]
@dtkaplan @rpruim Hi

just to inform you that I intend to submit a new version of `labelled` by the end of the week or early next week.

Regards

**Comment by rpruim** [comment]
Thanks for the heads up.  I haven't had a chance yet to take a look, but I'll see if I can do that in the next couple days.

**Comment by larmarange** [comment]
thanks

**Comment by rpruim** [comment]
I plan to submit to CRAN later today.  I'm going to see if I can take care of a couple other things at the same time.  If not, I'll just do an update to fix this issue.

**Comment by larmarange** [comment]
Thanks. Ï will postpone the release of `labelled` for an extra day or two.

**Comment by nicholasjhorton** [comment]
Thanks to you both for your work on this front.

**Comment by larmarange** [comment]
Great. Thanks a lot
