### ISSUE TITLE
Dependency on maptools and rgeos

### ISSUE THREAD

**Issue by olivroy** [ProjectMOSAIC/ggformula#168]
Do you plan to submit a patch to CRAN before October 16 to avoid archiving the package?

https://github.com/r-spatial/evolution#readme

**Comment by rpruim** [comment]
It appears that this is only used in dontrun section of an example, so removing this should be fairly easy. I'm hoping to get a new version of the package to CRAN perhaps as soon as today or tomorrow.  It is other things that will determine how long this takes.

**Comment by nicholasjhorton** [comment]
@rpruim many thanks for your work on this front: it's greatly appreciated.

**Comment by rpruim** [comment]
New example for `gf_sf()`:

``` r
suppressPackageStartupMessages(library(ggformula))
example(gf_sf)
#> 
#> gf_sf> if (requireNamespace('maps', quietly = TRUE)) {
#> gf_sf+ library(maps)
#> gf_sf+ world1 <- sf::st_as_sf(map('world', plot = FALSE, fill = TRUE))
#> gf_sf+ gf_sf(data=world1)
#> gf_sf+ 
#> gf_sf+ world2 <- sf::st_transform(
#> gf_sf+   world1,
#> gf_sf+   "+proj=laea +y_0=0 +lon_0=155 +lat_0=-90 +ellps=WGS84 +no_defs"
#> gf_sf+ )
#> gf_sf+ gf_sf(data = world2)
#> gf_sf+ }
```

![](https://i.imgur.com/UyI76Yl.png)

<sup>Created on 2023-10-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rpruim** [comment]
Improved version.  Apparently if(){} blocks intermediate graphical output.

``` r
suppressPackageStartupMessages(library(ggformula))
example(gf_sf)
#> 
#> gf_sf> if (requireNamespace('maps', quietly = TRUE)) {
#> gf_sf+   library(maps)
#> gf_sf+   world1 <- sf::st_as_sf(map('world', plot = FALSE, fill = TRUE))
#> gf_sf+   gf_sf(data=world1)
#> gf_sf+ }
```

![](https://i.imgur.com/zskTf6r.png)

    #> 
    #> gf_sf> if (requireNamespace('maps', quietly = TRUE)) {
    #> gf_sf+   world2 <- sf::st_transform(
    #> gf_sf+     world1,
    #> gf_sf+     "+proj=laea +y_0=0 +lon_0=155 +lat_0=-90 +ellps=WGS84 +no_defs"
    #> gf_sf+   )
    #> gf_sf+   gf_sf(data = world2)
    #> gf_sf+ }

![](https://i.imgur.com/9uNqnNg.png)

<sup>Created on 2023-10-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rsbivand** [comment]
@rpruim  rgeos and maptools were archived yesterday, so please do move to submit an updated version of ggformula as soon as possible. See https://github.com/r-spatial/evolution https://r-spatial.github.io/evolution/ for details.
