### ISSUE TITLE
Provide alternative syntax for mapping non-positional attributes/aesthetics

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#21]
I'm thinking of something like this:
```r
gf_point( y ~ x, color = ~ a, data = mydata)
```

Advantages:
  * should be easier to do on the fly computations (fewer parens)
  * less text parsing of formula
  * formulas can get pretty big when there are lots of attributes to set
  * easier to convert between mapping and setting when `attribute = value` is used for setting.
  * avoid needing `::` for some cases.

Eventually, we can decide if we want to support a **one true way** or continue to support both ways of specifying attribute-mapping.

**Comment by dtkaplan** [comment]
One thing that would be nice about your proposed format is that one could more easily write functions that make use of gf_  functions. But I haven't started using rlang yet, so maybe that's the way to go anyway.

For the present, I'd like to keep supporting the formula-attribute style. My (untested) hypothesis is that it will transfer more easily to modeling.

**Comment by rpruim** [comment]
I just created a first draft of this.  It works by going through ... and searching for items of the form `foo = ~bar` and adding `foo = bar` to `aes()`.

If we wanted to do the extra work of listing all the eligible aesthetics when we create these functions, we could prehaps create better documentation and error/warning messages.  For now, you will simply get what `ggplot2` reports if you try to use a meaningless aesthetic.

```r
gf_point(length ~ width, data = KidsFeet, shape = ~ domhand, color = ~ sex, alpha = 0.5, verbose = TRUE)
## ggplot(data = KidsFeet) + 
##   geom_point(aes(y = length, x = width, color = sex, shape = domhand), alpha = 0.5) 
```

For now, `ggformula` is agnostic about which way mapped attributes should be described.  But I've become less and less of a fan of adding `attribute:value` or `attribute::expression` into the formula.  So I'm going to give the new syntax a try for awhile.

**Comment by rpruim** [comment]
The new syntax help up well in our two recent workshops.  I'm going to close this since there are no known issues at this point.
