### ISSUE TITLE
create minimal R sheet for ggformula

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#24]

**Comment by rpruim** [comment]
First draft of this is in the `mosaic` package.  Improvements to come.

**Comment by dtkaplan** [comment]
I'm not seeing this in either `mosaic` or `ggformula`

**Comment by rpruim** [comment]
I may need to do a push.

**Comment by rpruim** [comment]
Pushed beta branch of mosaic a moment ago.
