### ISSUE TITLE
Error in how gf_dist() plots distributions with a grouping indicator

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#30]
To get all the features of `mosaic::plotDist()`, I'd need to figure out how to get at the x-range of the plotting windows.

**Comment by nicholasjhorton** [comment]
Since the internals of plotFun() are hidden from the user, can this be deferred for the moment?  (Or does the need to annotate plots force the issue?)

> On Jun 23, 2017, at 8:44 AM, Randall Pruim <notifications@github.com> wrote:
> 
> To get all the features of plotFun(), I'd need to figure out how to get at the x-range of the plotting windows.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by rpruim** [comment]
`plotDist()` is the issue, not `plotFun()` (I mistyped because I'm thinking about both of these in the `ggformula` setting.)

It would be nice to have a version of `plotDist()` that can be used as a layer in `ggformula` plots.

**Comment by rpruim** [comment]
Have first draft working:

```r
gf_histogram( ..density.. ~ rnorm(100), bins = 20) %>%
  gf_dist("norm", color = "red")
```
![image](https://user-images.githubusercontent.com/722231/27484217-673b8910-57f6-11e7-8310-75ef627c5b03.png)

**Comment by rpruim** [comment]
I think this is in good shape.  The following examples all work as expected (by me;-)

```r
gf_histogram( ..density.. ~ rnorm(100), bins = 20) %>%
  gf_dist("norm", color = "red")

gf_dist(dist = "norm", color = "red")
gf_dist("norm", color = "red")
gf_dist("norm", color = "red", kind = "cdf")
gf_dist("norm", fill = "red", kind = "histogram")
gf_dist("norm", color = "red", kind = "qqstep", resolution = 25) %>%
gf_dist("norm", color = "black", kind = "qq", resolution = 25)
# This doesn't work well because size has two meanings
gf_dist("binom", size = 20, prob = 0.25)
# This is better
gf_dist("binom", params = list(size = 20, prob = 0.25))
```

**Comment by nicholasjhorton** [comment]
Is it possible to generate the equivalent of:

library(mosaic)
plotDist("chisq", df = 2, groups = x > 7, type = "h")
<img width="466" alt="screen shot 2018-06-04 at 3 00 54 pm" src="https://user-images.githubusercontent.com/530542/40936079-1e0c4464-6808-11e8-81f0-edcfa884b827.png">

**Comment by nicholasjhorton** [comment]
This doesn't look correct:

library(mosaic)
gf_dist("norm", fill = ~ (x > 1), kind = "histogram")

<img width="482" alt="screen shot 2018-06-04 at 4 50 27 pm" src="https://user-images.githubusercontent.com/530542/40940978-77b6dda8-6817-11e8-91d0-c922bbf4c9dc.png">

**Comment by rpruim** [comment]
Looks like `stat(density)` (formerly `..density..`) is rescaling density separately in each color group.  I'll have to see if there is an option to say "don't do that."

**Comment by mchien20** [comment]
Any guidance for any other approaches to this problem?
Thanks in advance,
Margaret

**Comment by rpruim** [comment]
Back to the question regarding chi-squared: This is relatively easy -- just need to use the area geom.

I think I don't want to make that the default geom, however, since I like to be able to overlay density curves on other layers, and the line geom works better for that.

``` r
library(ggformula)
#> Loading required package: ggplot2
#> 
#> New to ggformula?  Try the tutorials: 
#>  learnr::run_tutorial("introduction", package = "ggformula")
#>  learnr::run_tutorial("refining", package = "ggformula")
gf_dist("chisq", df = 3, fill = ~ (x > 3), geom = "area")
```

![](https://i.imgur.com/GZR1n7n.png)

Created on 2018-06-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by rpruim** [comment]
`geom_histogram()` doesn't use `group`, but there is an x-stat available that can be used for fill.  I'm guessing this is the center of each bin and that each bin will always get just one color.  (You can use `boundary` to force your cutoff to be at a bin edge.)

``` r
library(mosaic)
gf_dist("norm", fill = ~ (stat(x) > 1), kind = "histogram")
```

![](https://i.imgur.com/OV0k8Ja.png)

Created on 2018-06-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by rpruim** [comment]
Note: This requires `ggplot2` version 2.3.

**Comment by rpruim** [comment]
See https://github.com/tidyverse/ggplot2/issues/2707#issuecomment-398855393 for more info.
