### ISSUE TITLE
Column names in df_stats() output

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#36]
Currently, `df_stats()` gets its names in one of three ways.  First applicable method wins.

 1. If the user provides a name, use that, enumerating when there is more than one component.

 2. If the stat function names its output, use that.

 3. Else a name is created from the name of the function and the variable it is applied to.  The `long_names` argument controls the format used.

```r
foo <- function(x) c(the_mean = mean(x), the_median = median(x))

df_stats(age ~ sex, data = HELPrct, foo)
##      sex the_mean the_median
## 1 female 36.25234         35
## 2   male 35.46821         35

df_stats(age ~ sex, data = HELPrct, center = foo)
##      sex  center1 center2
## 1 female 36.25234      35
## 2   male 35.46821      35

df_stats(age ~ sex, data = HELPrct, mean)
##      sex mean_age
## 1 female 36.25234
## 2   male 35.46821

df_stats(age ~ sex, data = HELPrct, mean, long_names = FALSE)
##      sex     mean
## 1 female 36.25234
## 2   male 35.46821
```

Decisions to make:

 * do we like this naming convention
 * should the default be `long_names = TRUE` or `long_names = FALSE`?

Note: there is also a `nice_names = TRUE` option that will force the names to be syntactically OK.

**Comment by rpruim** [comment]
Last chance to discuss the output format for `df_stats()`.

**Comment by dtkaplan** [comment]
Yes, we do need to make a decision. I propose this priority sequence for setting the name(s)

a. For stats that return a single component
    1. If the user provides a name, use that name.
    2. If the stat function names its output, use that name.
    3. If the stat function does *not* name its output, use the name of the function.
b. For stats that return multiple components
    1. If the user provides a name, use that name suffixed with the names provided by the stat (or, for stats that don't give names, like `range()`, use the component number.
    2. If the user doesn't provide a name and the output is named, use those names (even though they will be "bare".
    3. If the stat function does *not* name its output, use the name of the function suffixed by the component number.

This present behavior already complies

```r
> ggformula::df_stats(hp ~ cyl, data = mtcars, hp_mean = mean)
  cyl   hp_mean
1   4  82.63636
2   6 122.28571
3   8 209.21429
> ggformula::df_stats(hp ~ cyl, data = mtcars, hp_ = range)
  cyl hp_1 hp_2
1   4   52  113
2   6  105  175
3   8  150  335 
```

But not this:
```r
> ggformula::df_stats(hp ~ cyl, data = mtcars, hp_ = coverage(0.95))
  cyl   hp_1    hp_2
1   4  54.50 112.000
2   6 105.75 167.200
3   8 150.00 311.925
```
The names should be `hp_lower` and `hp_upper`, since those are the names provided by the function produced the function produced by `coverage(0.95)`.

This present behavior also complies with b.2.
```r
> ggformula::df_stats(hp ~ cyl, data = mtcars, coverage(0.95), ci.mean())
  cyl  lower   upper     lower     upper
1   4  54.50 112.000  68.57236  96.70037
2   6 105.75 167.200  99.84850 144.72293
3   8 150.00 311.925 179.78111 238.64746
```

Yes, it's annoying that the names are repeated. When using multiple stats, the user *should* give names. But let's encourage the user to decide what the prefix should be.

**Comment by rpruim** [comment]
I think something like this should be doable.

@dtkaplan, I'd prefer reproducible examples that don't rely on `coverage()` and `ci.mean()` (which are where?)  That will speed up the testing.

**Comment by dtkaplan** [comment]
Good point.  Here's a reproducible example:

```r
> myfun <- function(x) { c(lower = 0, upper = 10)}
> ggformula::df_stats(hp ~ cyl, data = mtcars, myfun)
  cyl lower upper
1   4     0    10
2   6     0    10
3   8     0    10
> ggformula::df_stats(hp ~ cyl, data = mtcars, my_name_ = myfun)
  cyl my_name_1 my_name_2
1   4        0       10
2   6        0       10
3   8        0       10
```

The names in the second example should be `my_name_lower` and
`my_name_upper`.

The `coverage()` and `ci.mean()` and other functions are currently in the
`projectMOSAIC/mosaicModel` package, which can now be installed cleanly
with `install_github`. The function definitions are here.
<here.https://github.com/ProjectMOSAIC/mosaicModel/blob/master/R/interval_statistics.R>
I'm
happy to move these to the same package that `df_stats()` lives in. But I'm
thinking that won't be `ggformula` in the long run.

**Comment by rpruim** [comment]
@dtkaplan 's example reformatted.

```r
## ```r
myfun <- function(x) { c(lower = 0, upper = 10)}
ggformula::df_stats(hp ~ cyl, data = mtcars, myfun)
##   cyl lower upper
## 1   4     0    10
## 2   6     0    10
## 3   8     0    10
ggformula::df_stats(hp ~ cyl, data = mtcars, my_name_ = myfun)
##   cyl my_name_1 my_name_2
## 1   4        0       10
## 2   6        0       10
## 3   8        0       10
```

**Comment by rpruim** [comment]
I think I have a reasonable solution.  You can even choose your separator (default is underscore).
```r
myfun <- function(x) { c(lower = 0, upper = 10) }
myfun0 <- function(x) { c(0, 10) }
df_stats(hp ~ cyl, data = mtcars, 
                    myname = myfun, 
                    myfun, 
                    anothername = myfun0,
                    myfun0,
                    mean, 
                    mn = mean)
##   cyl myname_lower myname_upper myfun_hp_lower myfun_hp_upper anothername_1 anothername_2 myfun0_hp_1
## 1   4            0           10              0             10             0            10           0
## 2   6            0           10              0             10             0            10           0
## 3   8            0           10              0             10             0            10           0
##   myfun0_hp_2   mean_hp        mn
## 1          10  82.63636  82.63636
## 2          10 122.28571 122.28571
## 3          10 209.21429 209.21429
```

**Comment by rpruim** [comment]
Small revision.  I think this matches @dtkaplan 's spec better:
```r
df_stats(hp ~ cyl, data = mtcars, 
                    myname = myfun, 
                    myfun, 
                    anothername = myfun0,
                    myfun0,
                    mean, 
                    mn = mean)
##   cyl myname_lower myname_upper lower upper anothername_1 anothername_2 myfun0_hp_1 myfun0_hp_2   mean_hp
## 1   4            0           10     0    10             0            10           0          10  82.63636
## 2   6            0           10     0    10             0            10           0          10 122.28571
## 3   8            0           10     0    10             0            10           0          10 209.21429
##          mn
## 1  82.63636
## 2 122.28571
## 3 209.21429
```
