### ISSUE TITLE
Put ggformula on CRAN

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#4]
Danny's plan of action:

The vignette needs much work. I can do this, but not for two weeks. How
about this plan:

1. Put it on CRAN now.
2. Danny fixes the vignette.
3. We write an rbloggers post.

**Comment by rpruim** [comment]
I've substantially modified the vignette.  It can receive another revision, but I think it is appropriate for CRAN now.

**Comment by rpruim** [comment]
What's on the to do list before we push this to CRAN?  Another spin through the vignette?  Any features to add or bugs to fix?

**Comment by rpruim** [comment]
On CRAN now.

**Comment by dtkaplan** [comment]
That's great!

**Comment by rpruim** [comment]
Better version coming with next CRAN release.  I think I'm about ready to merge my developmental branch into master on github.  The only thing lost at this point is `verbose = TRUE`, but I'm not sure that that is the most important thing.
