### ISSUE TITLE
Add support for x ~ 1 where ~ x is currently required.

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#40]
This was suggested by @nicholasjhorton.

I think it should be possible to essentially convert `x ~ 1` into ` ~ x` before processing the formula.  I'm imagining that a literal `1` will be required here and not something that evaluates with a single unique value.   Would that suffice?

**Comment by rpruim** [comment]
Converting the formula is easy.  The only question is when to do it.  I've adopted the following strategy:  If a 1-sided formula is an option, then converting `y ~ 1` into `~ y`, else (as for `gf_point()`, for example) do not convert.

Using this logic, these all work with acceptable behavior:
```r
gf_density(age ~ 1, data = HELPrct)
gf_point(age ~ 1, data = HELPrct)
gf_histogram(age ~ 1, data = HELPrct)
gf_histogram(..density.. ~ age, data = HELPrct)
```
Histograms are the tricky case since they allow either a 1-sided or a 2-sided formula.

**Comment by rpruim** [comment]
Note:  I would not promote this syntax in an introduction to `ggformula`.  I would only show it as an **alternative** in a context where one is using something like `lm(y ~ 1)`.

**Comment by nicholasjhorton** [comment]
I need to push back here a bit. Why not just teach "var ~ 1"?  That syntax works with everything unlike "~ var" which doesn't work for lm(). 

All the best,

Nick

**Comment by rpruim** [comment]
I guess you can do it as you like when you use the package, but I would not put the new syntax into the general introduction (in the vignette, for example).

I don't find `gf_histogram(x ~ 1)` at all compelling, especially if you haven't ever seen `lm(y ~ 1)`, which is already a bit forced.

On the contrary, I fear it will disrupt thinking about the `y ~ x` form used otherwise systematically throughout the plotting system.

**Comment by rpruim** [comment]
The current implementation does not support `y ~ 1 | z`.

**Comment by rpruim** [comment]
I've extended the formula conversion to handle more cases.

```r
ggformula:::standard_formula(age ~ 1 | sex ~ .)
## ~age | sex ~ .
ggformula:::standard_formula(age ~ 1 | . ~ sex)
## ~age | . ~ sex
ggformula:::standard_formula(age ~ 1 | ~ sex)
## ~age | ~sex
ggformula:::standard_formula(age ~ 1 | sex)
## ~age | sex
```
