### ISSUE TITLE
A cost of supporting attribute:value syntax in the main formula

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#41]
I think this pretty much interferes with the following reasonable syntax:

```r
gf_point(power(1:100) ~ 1:100)
```
at least as currently implemented.

Is it worth removing `attribute:value` support to handle examples like this?

**Comment by nicholasjhorton** [comment]
The attribute:value syntax has been criticized by some when I've tried to pitch ggformula. 

Is there an alternative to attribute:value that you have in mind?  I presume that attribute=value won't fly. 

All the best,

Nick

**Comment by rpruim** [comment]
The alternative is to not put these in the formula but to use arguments of the form `attribute = ~ value`.  That is already implemented  and is the way I've been doing things.

`y ~ x + a = b` is not syntactically value because it looks like an assignment with a bad rhs.

We can probably get `:=` to work by writing a function.  I think Hadley did something like this in `ggvis`.  But we would need to write a new formula parser because the order of operations is wrong. 
 Out of the box you get
```r
y ~ x + a := b
Error in `:=`(y ~ x + a, b) : could not find function ":="
```

@dtkaplan, want to make a pitch for the `:` syntax?

**Comment by nicholasjhorton** [comment]
The existing alternative works for me. 

All the best,

Nick

**Comment by rpruim** [comment]
The real question is about whether we should remove the `attribute:value` option.

**Comment by dtkaplan** [comment]
If there is no way to do both, then do away with attribute:value. In any
event, that will make checkr easier to use with ggformula statements.

**Comment by rpruim** [comment]
Nice to know there is another advantage as well.  

Attempting to do both would probably lead to ambiguous cases and would at least require some rewriting.

Eliminating the : syntax will require some changes to vignettes and other documentation.  So this isn't a pain free move.

**Comment by rpruim** [comment]
Turning off the : syntax parsing was relatively easy.
```r
gf_point(1:10 ~ 1:10)          # this produces the plot you would expect
gf_point(1:10 ~ 1:10, color = "red")    # now with red dots
gf_point(1:10 ~ 1:10 + color:"red")     # this no longer works.
## Error: Invalid formula type for gf_point.
```

I did think of a potential way to eat our cake and have it too:  We could parse the : stuff only in the parts not defined by the positional elements of the formula.  But this will be a pain for functions that allow multiple formula shapes and would require more thought/work.

If we miss the : parsing, we can consider reintroducing it down the road.  For now, it is gone.
