### ISSUE TITLE
Proposed changes to df_stats

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/ggformula#44]
I'd like to modify for `df_stats()` always to return a dataframe-like object. Currently, when the formula is one-sided, `df_stats()` returns a vector not a dataframe.

Not about modifying `df_stats` ...

Following the use-your-own-stat-function style of `df_stats`, I'm planning to add some functions that calculate confidence intervals on simple stats like `mean`, `median`, `sd`.  Some questions:

1. Should I put these in the `ggformula` package? Seems odd to do so, but that's where `df_stats()` lives.
2. It would be nice to have a `level =` argument for these functions. I can't simply put this in `fargs` in `df_stats`, since that will barf for functions that don't take a `level` argument. I'm open to other ideas. For now, my plan is to write to versions of each function, one like `ci_mean` which directly does the calculation, and another like `ci_mean_level(0.95)` which takes the level as an argument and returns the proper form of `ci_mean` for a calculation at that level.

@rpruim I love how you used `model.frame()` with the side effect of causing `na.omit()` to run on the data being processed. This makes it completely consistent with the NA behavior of `lm()`, etc.

**Comment by rpruim** [comment]
@dtkaplan, I'm not seeing the behavior you describe:

```r
df_stats(~ age, data = HELPrct, mean, median)
##   mean_age median_age
## 1 35.65342         35
df_stats(~ age, data = HELPrct, mean, median) %>% class()
## [1] "data.frame"
df_stats( age ~ 1, data = HELPrct, mean, median) %>% class()
## [1] "data.frame"
```

**Comment by rpruim** [comment]
`df_stats()` does not require that the functions be in the `ggformula` package.  So at the level of functionality, it doesn't matter where they are located.  Possible reasons to include them in `ggformula`:

  * If they are useful for examples or in our vignette
  * If they are likely to be used in conjunction with plotting
  * If they are not specific to other tasks and don't have another natural home.

Of course, to be included in `ggformula` now, they should be well thought out, tested, and documented.  Else we should wait until the next-next release.

**Comment by rpruim** [comment]
I'm not entirely sure I understand your comment about `fargs`.  Are you worried about combining functions that do and don't take `level` in the same call to `df_stats()`?

Note: if the functions take `...`, they should handle an unused `level` argument just fine.

We could check the elements of `fargs` against the formals of the functions used, but that would cause problems for functions that use `...` to pass important arguments on to other functions, so I don't like that idea, at least not as a default.

**Comment by dtkaplan** [comment]
@rpruim I've written several of the interval statistics. 

* `ci.mean()`
* `ci.median()`
* `ci.sd()`
* `coverage()`
* `ci.proportion()` which goes along with `proportion()`

For the moment, they are stashed in `mosaicModel` in the file `interval_statistics.R`.  Use them like this:

```r
mtcars %>% df_stats(hp ~ cyl, ci.mean())
##   cyl     lower     upper
## 1   4  68.57236  96.70037
## 2   6  99.84850 144.72293
## 3   8 179.78111 238.64746
```

You can give an argument to set the confidence level, e.g. `level = 0.80`

* I don't think they belong in `mosaicModel`. We can decide later whether to move them to `ggformula`
* `proportion()` and `ci.proportion()`  can take an optional argument `nm` identifying the level of the categorical variable to use in calculating the proportion. They also take a `level` argument to give the confidence level --- interesting how the nomenclature conflicts here between a "level" of a variable and a "level" for a confidence interval.
* The naming of the output isn't very nice. I like this existing behavior:
```r
mtcars %>% df_stats(hp ~ cyl, mean)
##   cyl   mean_hp
## 1   4  82.63636
## 2   6 122.28571
## 3   8 209.21429
```

Which can, if desired, be overridden by using a named argument: e.g. `my_preferred_name = mean`
But this doesn't carry over well to statistics that return multiple numbers, even when those numbers are named.

A statement in this form loses the variable name, but does pick up the statistic names
```r
mtcars %>% df_stats(hp ~ cyl, ci.mean())
##   cyl     lower     upper
## 1   4  68.57236  96.70037
## 2   6  99.84850 144.72293
## 3   8 179.78111 238.64746
```

But we can't put it back by explicit naming, since the statistic names are not picked up when an explicit name is given:
```r
mtcars %>% df_stats(hp ~ cyl, hp_mean = ci.mean())
##   cyl  hp_mean1  hp_mean2
## 1   4  68.57236  96.70037
## 2   6  99.84850 144.72293
## 3   8 179.78111 238.64746
```

**Comment by rpruim** [comment]
This has gotten rambly and unrelated to the issue originally described.

@dtkaplan, I'm closing this since I was never able to recreate the original problem you thought you had, so I don't see a reason to redesign `df_stats()` at the moment.

Let's open new issues focussed on particular things, if they exist.

**Comment by rpruim** [comment]
As for your new functions -- I can't figure out what you were thinking when you named that argument `nm`.  It conjures nothing meaningful to me.  How about `success`, which matches what we do elsewhere in `mosaic` and is the traditional name for this.

Names matter.

**Comment by rpruim** [comment]
See #36 for an issue explicitly about column names,
