### ISSUE TITLE
Friends for `df_stats()`

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/ggformula#47]
I've written a wrapper around `mosaic::tally()` which works with piped-in data (or `data = `) and returns a data frame as output. This has two names: `df_props()` and `df_counts()`. Currently, these are in the `mosaicModel` package, but I don't think they should live there. Among the options ...

1. Put them in `ggformula`
2. Create a `mosaicdf` (`mosaicDf` ?)  which contains all the `df_` functions.

I considered integrating them with `df_stats()`, but decided not.  Giving them separate names is (1) likely easier for students to assimilate, (2) keeps `df_stats()` cleaner, and (3) leaves `df_stats()` as explicitly about statistics of a single variable.

**Comment by rpruim** [comment]
These definitely do not belong in `mosaicData`.  Please don't clutter up the repo with cruft that doesn't belong in that package.  If you haven't pushed, I'd rather you not push to the public repo.

**Comment by rpruim** [comment]
It would be easier to decide where these functions go if there were a plan in place for what functions will be created.

**Comment by rpruim** [comment]
If you have already put things into `mosaicData`, please remove them.  I don't want cruft in there as we get ready for a CRAN release.

**Comment by dtkaplan** [comment]
I meant to say that I created them in `mosaicModel`. They are in the
`issue003` branch. I edited my previous post to correct things to
`mosaicModel`, so don't think that you're crazy if you look back at that
post.

**Comment by rpruim** [comment]
OK.  That at least makes more sense.

Still thinking about where these really belong.

**Comment by rpruim** [comment]
@dtkaplan, is there a reason that the following doesn't server your purpose?
```r
> df_stats( substance ~ sex, data = HELPrct, prop, count)
     sex prop_substance count_substance
1 female      0.3364486              36
2   male      0.4075145             141
```

**Comment by rpruim** [comment]
Note: This works too:

```{r}
> df_stats( sex ~ substance, data = HELPrct, prop, count, fargs = c(level = "male"))
  substance  prop_sex count_sex
1   alcohol 0.7966102       141
2   cocaine 0.7302632       111
3    heroin 0.7580645        94
```

But I wonder if `success` is a better name than `level` for this argument.

**Comment by dtkaplan** [comment]
There's always a question of whether I'm thinking too rigidly. But I like having the proportion for each of the levels:
```r
> df_props( substance ~ sex, data = HELPrct)
# A tibble: 6 x 3
# Groups:   substance [3]
  substance    sex proportion
*    <fctr> <fctr>      <dbl>
1   alcohol female  0.3364486
2   cocaine female  0.3831776
3    heroin female  0.2803738
4   alcohol   male  0.4075145
5   cocaine   male  0.3208092
6    heroin   male  0.2716763
> df_props( sex ~ substance, data = HELPrct)
# A tibble: 6 x 3
# Groups:   sex [2]
     sex substance proportion
* <fctr>    <fctr>      <dbl>
1 female   alcohol  0.2033898
2   male   alcohol  0.7966102
3 female   cocaine  0.2697368
4   male   cocaine  0.7302632
5 female    heroin  0.2419355
6   male    heroin  0.7580645
```

And to have the option of formatting the output as a cross tabulation:

```r
> df_props( sex ~ substance, data = HELPrct, wide = TRUE)
     sex substance_alcohol substance_cocaine substance_heroin
1 female         0.2033898         0.2697368        0.2419355
2   male         0.7966102         0.7302632        0.7580645
```

**Comment by rpruim** [comment]
So are counts and proportions the only things that work like this, or is there an underlying analog to `df_stats()` that we should make that can generate each of these.

Each of these output formats could add an extra column giving the function being computed, as a reminder when there is one and as an important identifier when there is more than one.

It seems like the process would be the same for any function of two vectors.  This could allow for something like

```r
df_stat2(age ~ cesd | substance, cor)
```
to compute correlations, for example.

**Comment by rpruim** [comment]
I've thought about this a bit more and decided I wasn't thinking too clearly when I thought `cor()` and @dtkaplan's functions might readily share the same infrastructure.  They have a fundamental difference:

  * `cor()` take two vectors as input and produces a single value as a response (for each group)

  * proportions and counts as @dtkaplan imagines them are functions that take a single vector as input and return more than one number.  In that way they are really more like `favstats()` and could potentially be handled by `df_stats()` with the proper function -- a version that can output all of the counts and/or proportions instead of just for the success level.

**Comment by rpruim** [comment]
Here is another approach.  It naturally generates the wide format above.
```r
df_stats( substance ~ sex, data = HELPrct, proportions)
##      sex prop_alcohol prop_cocaine prop_heroin
## 1 female    0.3364486    0.3831776   0.2803738
## 2   male    0.4075145    0.3208092   0.2716763
df_stats( substance ~ sex, data = HELPrct, counts)
##      sex num_alcohol num_cocaine num_heroin
## 1 female          36          41         30
## 2   male         141         111         94
```
This could be followed by a call to `tidyr::gather()` (and some renaming) to get the narrow version.  We could build this into `df_stats()`, but for the moment (without the renaming):

```r
df_stats( substance ~ sex, data = HELPrct, counts) %>% tidyr::gather(substance, count, - sex)
##      sex   substance count
## 1 female num_alcohol    36
## 2   male num_alcohol   141
## 3 female num_cocaine    41
## 4   male num_cocaine   111
## 5 female  num_heroin    30
## 6   male  num_heroin    94
df_stats( substance ~ sex, data = HELPrct, proportions) %>% tidyr::gather(substance, proportion, - sex)
##      sex    substance proportion
## 1 female prop_alcohol  0.3364486
## 2   male prop_alcohol  0.4075145
## 3 female prop_cocaine  0.3831776
## 4   male prop_cocaine  0.3208092
## 5 female  prop_heroin  0.2803738
## 6   male  prop_heroin  0.2716763
```

What are the pros/cons of adding two specialty `df_` functions vs. adding `proportions()` and `counts()`?

**Comment by rpruim** [comment]
Still thinking...

@dtkaplan, could you live with this sort of naming scheme?
```r
> df_stats( age ~ sex, data = HELPrct, ggplot2::mean_se) %>% tidyr::gather(stat, value, - sex)
     sex stat    value
1 female    y 36.25234
2   male    y 35.46821
3 female ymin 35.51908
4   male ymin 35.05156
5 female ymax 36.98559
6   male ymax 35.88486
> df_stats( substance ~ sex, data = HELPrct, proportions) %>% tidyr::gather(stat, value, -sex)
     sex         stat     value
1 female prop_alcohol 0.3364486
2   male prop_alcohol 0.4075145
3 female prop_cocaine 0.3831776
4   male prop_cocaine 0.3208092
5 female  prop_heroin 0.2803738
6   male  prop_heroin 0.2716763
> df_stats( substance ~ sex, data = HELPrct, counts) %>% tidyr::gather(stat, value, -sex)
     sex        stat value
1 female num_alcohol    36
2   male num_alcohol   141
3 female num_cocaine    41
4   male num_cocaine   111
5 female  num_heroin    30
6   male  num_heroin    94
```

That should be pretty easy to implement, would work generally with any use of `df_stats()`, and reflects the "stat" part of the name of that function.

**Comment by rpruim** [comment]
Regardless of the decision about `df_props()` and `df_counts()`, I've added the wide vs long formatting option to `df_stats()`.

```r
df_stats( hp ~ cyl, data = mtcars, mean, median, range, format = "long")
##    cyl      stat     value
## 1    4   mean_hp  82.63636
## 2    6   mean_hp 122.28571
## 3    8   mean_hp 209.21429
## 4    4 median_hp  91.00000
## 5    6 median_hp 110.00000
## 6    8 median_hp 192.50000
## 7    4 range_hp1  52.00000
## 8    6 range_hp1 105.00000
## 9    8 range_hp1 150.00000
## 10   4 range_hp2 113.00000
## 11   6 range_hp2 175.00000
## 12   8 range_hp2 335.00000
```

**Comment by dtkaplan** [comment]
I'll have to think more about this idea of having a props function for
`df_stats()` that returns the proportion of each level in the variable on
which stats are being calculated. This would work for conditional
probabilities, but I don't see how it would work for joint probabilities.

I've always liked the `mosaic::tally()` structure, which does both
conditional and joint probabilities.

**Comment by rpruim** [comment]
The two approaches aren't mutually exclusive.  I've already implemented the "long" option for `df_stats()`, and I'm adding `props()` and `counts()` to `mosaic`, so those will be available.

We can decide independently about `df_props()` and `df_counts()` and where they belong.

Side note: my approach lets you do both at once:

```r
> df_stats( substance ~ sex + homeless, data = HELPrct, counts, props)
substance ~ sex + homeless
     sex homeless num_alcohol num_cocaine num_heroin prop_alcohol prop_cocaine prop_heroin
1 female homeless          20          14          6    0.5000000    0.3500000   0.1500000
2   male homeless          83          45         41    0.4911243    0.2662722   0.2426036
3 female   housed          16          27         24    0.2388060    0.4029851   0.3582090
4   male   housed          58          66         53    0.3276836    0.3728814   0.2994350
```

**Comment by rpruim** [comment]
@dtkaplan: Note that the `props()` function is not *for* `df_stats()`.  It has stand-along uses, but can also be used with `df_stats()`.  That is an important design feature.
