### ISSUE TITLE
default for gf_histogram()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/ggformula#48]
![screen shot 2017-07-16 at 8 56 04 am](https://user-images.githubusercontent.com/530542/28247740-a2e1277a-6a04-11e7-8dd4-0326f3fd244a.png)

Can the default for df_histogram() address the "Pick better value" message?  (Or is this fixed in a beta version of ggplot2()?)

**Comment by rpruim** [comment]
I guess we have to decide whether that behavior is "broken".  Hadley likes chatty software.  

We can set `bins = 30`, but I'd have to check what `bins = 30, binwidth = 2` does.  If that doesn't prefer `binwidth`, then this isn't really a solution.

**Comment by rpruim** [comment]
It works.  I've set the default value of bins to 25.  Have to go back and update FASt.
