### ISSUE TITLE
gf_boxplot support for 1 variable

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/ggformula#50]
gf_boxplot(~ age, data=HELPrct)

isn't supported, while

gf_boxplot(age ~ 1, data=HELPrct)

is suboptimal.  

While I'm not a fan of a single boxplot, it is still taught (and shows up in SDM4 in R chapter 3.

**Comment by rpruim** [comment]
There isn't a good way to do this without writing a new geom/stat because `geom_boxplot()` requires both `x` and `y` aesthetics.

So not sure what you are hoping for here.  If all you want is the boxplot, then you can do something like

```r
gf_boxplot( age ~ 1, data = HELPrct) %>% 
  gf_theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) %>% 
  gf_labs(x = "")
```

**Comment by nicholasjhorton** [comment]
If it were just me I would state that boxplots should also be used with side-by-side boxplots.  But unfortunately, several textbooks that we have examples for describe univariate boxplots as a way of displaying the five number summary + outliers.  

Could a gf_1boxplot() function be added?  I wouldn't object to a note in the documentation that a univariate boxplot is suboptimal.

**Comment by rpruim** [comment]
Doing that right probably isn't in the cards on the current time frame.  

One would want the boxplot to be horizontal so that it could play with other one-variable plots like `gf_density()`, etc. I think.

Remember, this is billed as a formula interface to `ggplot2` and `ggplot2` doesn't support this sort of thing.

We can keep this on the wish list.

**Comment by rpruim** [comment]
Note:  There are indications that this will be supported in a future `ggplot2`.  That's the time to add it here as well.

See, for example: https://github.com/tidyverse/ggplot2/pull/2292

**Comment by rpruim** [comment]
Looks like this has been merged into the main development of ggplot2 now (see https://github.com/tidyverse/ggplot2/pull/2292).  We should be able to support this once `ggplot2` goes to CRAN.

**Comment by rpruim** [comment]
This now works with `ggplot2` versions higher than 2.2.1:

```r
gf_boxplot( ~ length, data = KidsFeet)
```
