### ISSUE TITLE
query about gf_histogram() and the mosaic::xhistogram() center option

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/ggformula#51]
Is the center option supported?  If so, can an example be added to the documentation?

Also, what is ..ndensity..?  I would have thought that this was percentage, but it doesn't seem to be.

**Comment by rpruim** [comment]
As per the help for `geom_histogram()`:

### Computed variables
count
number of points in bin

density
density of points in bin, scaled to integrate to 1

ncount
count, scaled to maximum of 1

ndensity
density, scaled to maximum of 1

**Comment by rpruim** [comment]
`center` and `boundary` both work:

```r
gf_histogram(~age, data = HELPrct, binwidth = 5, color = "white")
gf_histogram(~age, data = HELPrct, binwidth = 5, color = "white", center = 42.5)
gf_histogram(~age, data = HELPrct, binwidth = 5, color = "white", boundary = 40)
```

Got a killer app for `center`?

**Comment by rpruim** [comment]
I'm not super fond of the defaults for `geom_histogram()`, but for now I've left them.  In the example above I set the color so that the edges of the bins are easier to match up to the x-axis.
