### ISSUE TITLE
replace dargs with an alternative syntax

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#55]
This example from #36 has me thinking about a different syntax for `df_stats()`:

```r
> ggformula::df_stats(hp ~ cyl, data = mtcars, coverage(0.95), ci.mean())
  cyl  lower   upper     lower     upper
1   4  54.50 112.000  68.57236  96.70037
2   6 105.75 167.200  99.84850 144.72293
3   8 150.00 311.925 179.78111 238.64746
```

In the example above, `coverage(.95)` returns a function, and that is a slick way to get this output.  But what if `df_stats()` could parse some thing like

```r
ggformula::df_stats(hp ~ cyl, data = mtcars, mean_sd(mult = 2))
```

to be equivalent to this
```r
ggformula::df_stats(hp ~ cyl, data = mtcars, mean_sd, dargs = list(mult = 2))
```
That would also remove the need for #53, shorten code, and make it easier for students (who typically don't know about lists).  It might also remove the need for functions like `confidence()` that return functions.  

Hmm.  Have to think about how to support `confidence(.95)` in the current use case if we do this.  (Or perhaps we simply don't allow it without saving the function to a name?)

**Comment by rpruim** [comment]
Well, what do you think?

```r
df_stats( age ~ sex, data = HELPrct, median,  mean(trim = 0.5))
##      sex median_age mean(trim = 0.5)_age
## 1 female         35                   35
## 2   male         35                   35
df_stats( age ~ sex, data = HELPrct, median, med2 = mean(trim = 0.5))
##      sex median_age med2
## 1 female         35   35
## 2   male         35   35
```
Current draft uses `fargs` as before (for all functions) if `length(fargs) > 0`.  Else it uses the new style.  I have to think a bit about naming, but if there are lots of args, it will probably be best if the user provides a name anyway.

**Comment by dtkaplan** [comment]
I like being able to use functions like `mean()` with the arguments optionally listed in parens. (Is that how it works? I wasn't able to build the master-branch version of ggformula.)

I thinking I'm seeing a compromise on the naming convention. If neither the argument nor the output of the stat function is named, construct a name using the RHS variable (like `median_age`). But if the argument has a name, use that as the name, pasting on any names on the vector returned by the stat.

**Comment by rpruim** [comment]
Basically I'm turning `df_stats( y ~ x, data, fun) into something like
```r
y %>% fun
```
using some magic from rlang and `substitute()`.  That handles inserting the the first argument into the call.

I'm trying to figure out if I should include some logic to handle various ways you might describe a function:
  * a name like `mean`
  * a "call" like `mean()` or `mean(trim = 0.2)`
  * a string like "mean"
  * an anonymous function like `function(x) mean(x, trim = 0.2)`
  * others?

That last one doesn't work currently (unless we have `fargs` and revert to the old way of evaluating), but I don't think is so bad to not support anonymous functions.  It's hard to detect the difference between bullets 2 and 3.  Both have class "call".
