### ISSUE TITLE
Inconsistency (bug?) between gg_dotplot and gg_histogram

### ISSUE THREAD

**Issue by jimstigler** [ProjectMOSAIC/ggformula#57]
When I make a histogram (gf_histogram(~ Sepal.Length | Species, data=iris, n=20)) I get counts on the y-axis. But when I try to make a dotplot using the same code (gf_dotplot(~ Sepal.Length | Species, data=iris, n=20) I get proportions on the y-axis. My expectation is to get counts for both. Am I doing something wrong?

**Comment by rpruim** [comment]
Your issue is not with `ggformula` but with `ggplot2::geom_dotplot()`.  The equivalent `ggplot2` code is 

```r
ggplot(data = iris) + geom_dotplot(aes(x = Sepal.Length)) + facet_wrap(~ Species)
```
and produces the same plot.

The trouble is that scaling is a challenge for dot plots.  It is probably best to just run off the y-axis labeling when creating dotplots.

**Comment by rpruim** [comment]
For reference.  Here is the same issue discussed at `ggplot2`:

https://github.com/tidyverse/ggplot2/issues/2203
