### ISSUE TITLE
replace weatherData

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#64]
`weatherData` has been pulled from CRAN.  I like weather data as an application for showing `gf_ribbon()`, `gf_pointrange()`, `gf_linerange()`, etc.

Plan: get our own weather data.  (Unless someone has a better suggestion for data to use.)

Problem: NOAA is currently down due to the shut down.

Stay tuned.

**Comment by nicholasjhorton** [comment]
Would the data in the macleish package suffice (https://cran.r-project.org/web/packages/macleish/index.html)?  This is on CRAN and stable.

**Comment by rpruim** [comment]
I'll look.  But I've also thought about including some data either in `mosaicData` or in `ggformula` so that we don't have to rely on external projects.  I was thinking I might grab some historical data from a few locations from NOAA or some other source.

**Comment by rpruim** [comment]
Hmm.  the main downside of that data is that there no comparison locations.  And it looks like the built in data sets are for a single year.  That might not provide the right kind of data to illustrate all of the features I'd like to highlight.  

Also, it depends on several additional packages, so it doesn't help me reduce the number of dependencies.

I think I'm still leaning toward getting our own data from a  few locations.

**Comment by rpruim** [comment]
I've decided to put a `Weather` data set into `mosaicData`.  Currently it has 5 cities and weather data from 2017.  I could consider adding/replacing cities or including additional years.  But there is some work involved in grabbing the data.

![image](https://user-images.githubusercontent.com/722231/35258656-f7496682-ffce-11e7-84ce-2bef372a52f9.png)

**Comment by rpruim** [comment]
`mosaicData` is on CRAN and includes the `Weather` data set, so I'm closing this.
