### ISSUE TITLE
possible feature to gf_bar?

### ISSUE THREAD

**Issue by jiyunson** [ProjectMOSAIC/ggformula#65]
Hi, I was wondering if there was a way to create proportion or percentage bar plots with gf_bar? I tried this (trying out stuff that would work in geom_bar) but it doesn't work:
```gf_bar(..count../sum(..count..) ~ substance, data = HELPrct)```

It would be nice if we could do something like:
```gf_bar(..prop.. ~ substance, data = HELPrct)```

Thanks!

**Comment by rpruim** [comment]
You can already do this now with

```r
  gf_col(..count../sum(..count..) ~ substance, data = HELPrct, stat = "count")
```

I could allow `y ~ x` as a formula-type in `gf_bar()`.  That would save needing to specify the stat.  I did that for `gf_histogram()`.  The main use was for density histograms.  But then I wrote `gf_dhistogram()` to make that easier.

By the way `..prop..` is available too, but it doesn't do exactly what you probably want it to do.

**Comment by nicholasjhorton** [comment]
Is it worthwhile adding this to a vignette?

  gf_col(..count../sum(..count..) ~ substance, data = HELPrct, stat = "count")

**Comment by rpruim** [comment]
No.  I'll have a better solution shortly ;-)  One little fine point to adjust and then I'll post an example.

**Comment by rpruim** [comment]
Similar to `gf_counts()` we now have `gf_props()` and `gf_percents()`:

```r
gf_props( ~ substance, data = HELPrct)
```
![image](https://user-images.githubusercontent.com/722231/35770128-a09f4d7e-08e3-11e8-9a89-46e6fcde3654.png)

**Comment by rpruim** [comment]
As a side effect of implementing this, I've also added some new arguments to all of the `gf_` functions:

```r
gf_point(births ~ date, data = Births78, 
  xlab = "DATE", ylab = "number of live births", 
  title = "Interesting patterns in the number of births", 
  subtitle = "(United States, 1978)", 
  caption = "Source: Social Security Administration")
```

![image](https://user-images.githubusercontent.com/722231/35770153-15b8957a-08e4-11e8-8d24-e6fe553ee80b.png)

**Comment by jiyunson** [comment]
This is awesome!

**Comment by rpruim** [comment]
I still have to update documentation and examples, but I expect this will be on github later today, and I'm supposed to submit to CRAN this weekend (related to another issue), so I expect this will be on CRAN soon, too.
