### ISSUE TITLE
Bug:  lines layers are not using optional attributes

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#70]
This is likely caused by a change to the way they are created -- using a geom instead of `layer()`.  

I haven't explored yet to see how easy/hard this will be to fix.

**Comment by rpruim** [comment]
This bug was introduced when moving `gf_abline()` et al to use their associated geoms (eg, `geom_abline()` rather than `layer()` to create layers.  This has the advantage of using the pre-processing in those geoms.  The downside is that it is hard to know what arguments are allowed in `...`.  (`layer` doesn't have `...`, so this problem doesn't arise in the same way there).

I was too aggressive in my attempt to avoid passing via `...` things that were ignored but generated a warning from `geom_abline()` and friends.  My current fix is to have an explicit list of arguments to discard before creating the call.  Another option would be to return to using `layer()` but to allow for a pre-function to mimic the things that are done in `geom_abline()` before it calls `layer()`.

Still mulling over the best approach to this issue.

**Comment by dtkaplan** [comment]
@rpruim I've added a branch issue070 which fixes this. As you'll see, it's just a couple of lines to bring any contents of `dots` back to the `layer_arguments` so they can be passed to `layer_fun`. I'm not sure how best to test the package, but the vignette seems to build OK (you should check this, since you're more sensitive to what the vignette is supposed to look like) and I get a clean check.  (I had to fix a couple of documentation things to get there.)

**Comment by rpruim** [comment]
@dtkaplan, do you know if there are any other geom or stat functions besides `geom_abline()`, `geom_hline()`, and `geom_vline()` that  do important computation before calling `layer()`?  Getting those three to work isn't that big a deal, but I'd like to do it in a way that works in other situations, too, if there are any.

Also, is there any reason we would want to allow for mixing and matching of geoms and stats with `gf_abline()` and friends?  I guess `geom_abline()` doesn't allow for that, but our `gf_abline()` has a `stat` argument that makes it seem like this should be possible.

These are the things I'm trying to sort through, not just how to get the three current functions in their most obvious use cases to work (that's the relatively easy part).  But I may just adopt your solution (or something like it) for now and revisit this if/when we have specific issues.

**Comment by rpruim** [comment]
rather than add the dots back in, my current solution avoids putting other things in that `geom_abline()` and friends don't use.  Seems to work for current set of use cases.

**Comment by dtkaplan** [comment]
@rpruim Good. Should we close this issue?

**Comment by rpruim** [comment]
I did some more testing and things seem to be working -- at least for the immediate use cases.

But I should at least update the documentation since not all of these arguments are actually used:

```r
> args(gf_abline)
function (object = NULL, gformula = NULL, data = NULL, geom = "abline", 
    stat = "identity", position = "identity", show.legend = NA, 
    show.help = NULL, inherit = FALSE, environment = parent.frame(), 
    xlab, ylab, title, subtitle, caption, ...) 
```
In particular, `geom_abline()` hard codes the geom, stat, and position.  So those arguments are simply ignored by `gf_abline()`.  That's not very elegant.

Let me spend a bit more time on this before I close the issue.

**Comment by rpruim** [comment]
So I did some experimenting with different solutions (and discovered that a few other things were either broken or at least suboptimal along the way).

The end result is a bit (but not a lot) of additional complexity in the factory function:

  * an additional optional argument `pre` gives an expression to be evaluated before anything else happens.  This lets us mimic what some of the geoms do.  In particular, I now create a position object for `gf_text()` and `gf_label()` when at least one of `nudge_x` or `nudge_y` is not 0.

  * the argument list of the resulting functions now includes more things explicitly (rather than burying them in `...`.  This should be helpful for users.  This required a bit of list merging and culling, the use of `formals()` and `match.call()`, etc.

**Before:**
```r
> args(gf_histogram)
function (object = NULL, gformula = NULL, data = NULL, geom = "bar", 
    stat = "bin", position = "stack", show.legend = NA, show.help = NULL, 
    inherit = TRUE, environment = parent.frame(), xlab, ylab, 
    title, subtitle, caption, ...) 
```

**After:**
```r
> args(gf_histogram)
function (object = NULL, gformula = NULL, data = NULL, geom = "bar", 
    stat = "bin", position = "stack", show.legend = NA, show.help = NULL, 
    inherit = TRUE, environment = parent.frame(), bins = 25, 
    binwidth, alpha, color, fill, group, linetype, size, xlab, 
    ylab, title, subtitle, caption, ...) 
```
Looking at this, I should probably reorder the arguments to put the more interesting ones near the front.

**Comment by rpruim** [comment]
I think this is a better order for the arguments:

```r
> args(gf_histogram)
function (object = NULL, gformula = NULL, data = NULL, bins = 25, 
    binwidth, alpha, color, fill, group, linetype, size, xlab, 
    ylab, title, subtitle, caption, geom = "bar", stat = "bin", 
    position = "stack", show.legend = NA, show.help = NULL, inherit = TRUE, 
    environment = parent.frame(), ...) 
```

**Comment by rpruim** [comment]
Putting more arguments in functions means more documentation is required.... I'll close this when I get all the new arguments documented.
