### ISSUE TITLE
Set alpha = 0.5 as default for histograms?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#72]
I don't like the default solid black fill for histograms.  It looks clunky and hides the guidelines that can be useful for estimating numerical values.

So I'm considering setting `alpha = 0.5` as the default.

Any reason not to do that?

![image](https://user-images.githubusercontent.com/722231/37246771-c4e1c954-247d-11e8-8ba9-81b655aa6b8e.png)
![image](https://user-images.githubusercontent.com/722231/37246781-dcf6ac26-247d-11e8-93e5-1a327f8a1202.png)

**Comment by dtkaplan** [comment]
I agree, completely.

**Comment by rpruim** [comment]
I've implemented this.
