### ISSUE TITLE
Function from layer_factory() fails to evaluate arguments.

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/ggformula#73]
The function produced by `layer_factory()` creates `extras_and_dots` but doesn't evaluate the things going into `extras_and_dots`. This causes a problem when there is an argument like `color ~ the_fun()`, where `the_fun()` returns a formula or a name.  Shiny apps often require such constructions.

```gf_point(mpg ~ hp, data = mtcars, color = ~ cyl)
# Doesn't work in master branch version of ggformula, but does in Issue070 branch
the_formula <- function() {
  res <- ~ cyl
  res
}
foo <- gf_point(mpg ~ hp, data = mtcars, color = the_formula())
foo # printing is where it doesn't work
```

I think I see the fix and will try.

**Comment by dtkaplan** [comment]
I made my attempt in Issue073. That fixes the problem in the example above, but **it does not** fix the problem with Shiny.  

For Shiny examples, see `devtools::install_github("StatPREP/StatPREPshiny")` and run the command `select_app()`. The apps work under Issue070, but not under other branches. The problem occurs when rendering a graphic.

It's really hard to debug in Shiny, except by using `cat()`. I'll have to figure out some strategy. But it might help @rpruim if you think about how the changes you made with respect to issue 070 might have caused the literal calls to be passed to the plot object, without the environment they need to resolve those calls.

**Comment by rpruim** [comment]
@dtkaplan, I moved the evaluation code until after `gformula` is known and set things to evaluate in the environment of `gformula`.   Minimal testing suggests that this still works as above.  Does it change anything in your shiny app?  If not, you can experiment by modifying the environment of `gformula` to see if there is a correct environment to use.

```r
# this still works after modification:
sexform <- function() { ~ sex}
gf_dens( ~ age, color = sexform(), data = HELPrct)
```

Here is the modified evaluation code.
```r
      # evaluate any items that are still calls
      for (n in seq_along(extras_and_dots)) {
        if (is.call(extras_and_dots[[n]]))
          extras_and_dots[[n]] <- eval(extras_and_dots[[n]], environment(gformula))
      }
```
This seems to work even in cases where there is no explicit formula, but that should probably be tested more thoroughly (unless the eventual solution doesn't need to set the environment here).

**Comment by rpruim** [comment]
@dtkaplan, is there any reason not to just evaluate all of the items in `extras_and_dots`?  Also, the gf_ functions have an environment argument.  That's a better option than `environment(gformula)`, I think.  I currently have this

```r
      extras_and_dots <-
        lapply(extras_and_dots, function(x) eval(x, environment))
```
Also, I've rearranged the order of some of this processing to keep related things closer together when the order didn't really matter.

**Comment by rpruim** [comment]
@dtkaplan, if there are still issues in your shiny app, please create a minimal reprex so we can debug and fix.  If things seem to be working after my recent edits, I'd like to know that we don't have any known bugs.

**Comment by rpruim** [comment]
I'm going to close this.  The minimal reprex sent by @dtkaplan seems to work as desired.  I've merged the changes on the Issue073 branch into master.
