### ISSUE TITLE
faceting with ordered factors

### ISSUE THREAD

**Issue by jiyunson** [ProjectMOSAIC/ggformula#80]
If we have an ordered factor and label it, it shows up great in a faceted histogram:

```
mtcars$hp3group <- factor(ntile(mtcars$hp, 3), levels = c(1:3), labels = c("low","med","high"), ordered = TRUE)

# orders correctly
gf_histogram(~ mpg, data = mtcars) %>%
  gf_facet_grid(hp3group ~ .)
```
![image](https://user-images.githubusercontent.com/30084828/39891231-dd2af478-5451-11e8-8344-b70fa9053330.png)

But then when we add group means to the faceted histogram, the levels get re-ordered alphabetically by label: 
```
mpg.stats <- favstats(mpg ~ hp3group, data = mtcars)

# when we add group means, orders alphabetically
gf_histogram(~ mpg, data = mtcars) %>%
  gf_facet_grid(hp3group ~ .) %>%
  gf_vline(xintercept = ~mean, data = mpg.stats, color = "orange") ``
```
![image](https://user-images.githubusercontent.com/30084828/39891289-fe02022c-5451-11e8-97a6-d9a00c7cd637.png)

It would be great if it could stay ordered even when we add other elements... Thanks! Ji

**Comment by rpruim** [comment]
This is an issue with `df_stats()`, not with the plotting.  `df_stats()` is using a character variable for `hp3group`.

This works just fine.

```r
mpg.stats2 <- mtcars %>%
  group_by(hp3group) %>%
  summarise(mean = mean(mpg))

gf_histogram(~ mpg, data = mtcars, inherit = FALSE) %>%
  gf_vline(xintercept = ~mean, data = mpg.stats2, color = "orange") %>%
  gf_facet_grid(hp3group ~ .) 
```
