### ISSUE TITLE
Allow y ~ . as a formula

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/ggformula#82]
Example usage:

```r
gf_point(Sepal.Length ~ Sepal.Width, data = iris) %>%
  gf_rugx( ~ Sepal.Width,  data = iris, color = "red") %>%
  gf_rugy(Sepal.Length ~ ., data = iris, color = "green")
```

**Comment by nicholasjhorton** [comment]
Does gf_rugy(Y ~ 1) also work?

**Comment by rpruim** [comment]
In minimal testing, it looks like it does.  But I would consider that undocumented behavior that may or may not persist.

**Comment by nicholasjhorton** [comment]
I'd encourage you to think more about this.  The parallels between 

gf_rugy(Y ~ 1) and lm(Y ~ 1) seem clearer to me than

gf_rugY(Y ~ .) and lm(Y ~ .)  

I worry that the proposal for Y ~ . is opening up a different can of worms.

**Comment by rpruim** [comment]
But note:

```r
gf_facet_grid(y ~ .)
```
This seems like a perfectly sane way to say that we have a y but no x.  `y ~ 1` looks like we want to plot something at position 1 in the x direction.  And while this currently works, `y ~ 2` gives a warning (because we are specifying a variable where . is expected -- 1 works because we promote `y ~ 1` to `~y`.)

We will need to revisit some of this formula wrangling for the next release.
