### ISSUE TITLE
Why no `interval` argument for `gf_spline()`?

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/ggformula#83]
`gf_smooth()` has an argument, e.g. `interval = "confidence"`. Wouldn't it make sense to add this for `gf_spline()`?

**Comment by rpruim** [comment]
What method do you propose for computing them?

**Comment by dtkaplan** [comment]
Bad idea for splines. They are constructed to have zero error, so there's not a way to get a confidence interval.
