### ISSUE TITLE
query about centering bins in gf_histogram()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/ggformula#89]
Can this be done?  It's been useful to replicate particular examples from textbooks.

**Comment by rpruim** [comment]
Is this what you want?
``` r
# histogram with centering
library(ggformula)
x <- rnorm(100, mean = 100, sd = 10)
gf_histogram(~ x, center = 0, binwidth = 4, color = "black")
```

![](https://i.imgur.com/34WoVjz.png)

``` r
gf_histogram(~ x, center = 2, binwidth = 4, color = "black")
```

![](https://i.imgur.com/deyNau0.png)

Created on 2018-06-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by rpruim** [comment]
I've added this to the examples:
``` r
library(ggformula)
x <- rnorm(1000)
gf_dhistogram( ~ x, binwidth = 0.5, center = 0, color = "black")
```

![](https://i.imgur.com/IvuVC63.png)

``` r
gf_dhistogram( ~ x, binwidth = 0.5, boundary = 0, color = "black")
```

![](https://i.imgur.com/WouMP8h.png)

Created on 2018-06-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
