### ISSUE TITLE
panel.lmbands()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/ggformula#90]
Is there an easy way to replicate the functionality of panel.lmbands() for ggformula plots?  This is used several times in some of the mosaic materials.

xyplot(age ~ cesd, panel = panel.lmbands, data = HELPrct)

<img width="459" alt="screen shot 2018-06-04 at 3 44 57 pm" src="https://user-images.githubusercontent.com/530542/40937934-43e394fc-680e-11e8-8417-332e4f0003da.png">

**Comment by nicholasjhorton** [comment]
My proposal would be to include examples of how to create this functionality using broom::augment() and not craft a separate layer for this.

**Comment by rpruim** [comment]
This exists already:
``` r
library(ggformula)
#> Loading required package: ggplot2
#> 
#> New to ggformula?  Try the tutorials: 
#>  learnr::run_tutorial("introduction", package = "ggformula")
#>  learnr::run_tutorial("refining", package = "ggformula")
library(mosaicData)
gf_point(length ~ width, data = KidsFeet) %>%
  gf_lm(interval = "confidence", fill = "red") %>%
  gf_lm(interval = "prediction", fill = "navy")
```

![](https://i.imgur.com/mLJCqRL.png)

Created on 2018-06-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by nicholasjhorton** [comment]
This looks great.  Could it be added to the vignette?  https://cran.r-project.org/web/packages/ggformula/vignettes/ggformula.html

**Comment by rpruim** [comment]
I've added something.  But I'm not sure the point of the vignette is to show every possible thing that can be done.

I've put this in the section on stats since these are using statistical transformations of the data.
