### ISSUE TITLE
query about mosaic::plotFun() support in ggformula

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/ggformula#91]
Can you please remind me where things stand in terms of a development plan for plotFun()?  Does it make sense to include this in ggformula?  (Has that already been done?)

**Comment by rpruim** [comment]
Currently we have two functions available: `gf_function()` and `gf_fun()`.  The second is more like `plotFun()`.  The first is more like `geom_function()`.  Both are useful.

@dtkaplan and I will be continuing our conversation about `mosaicModel` and plotting functions associated with model directly.

**Comment by rpruim** [comment]
I've added a short section about plotting functions to the vignette.
