### ISSUE TITLE
Warning Message about suggested packages in tutorials

### ISSUE THREAD

**Issue by bjcoleman** [ProjectMOSAIC/ggformula#92]
The data package `NHANES` is a suggested package for the tutorial, and so the command `learnr::run_tutorial("introduction", package = "ggformula")` produces the message `Error in library(NHANES) : there is no package called ‘NHANES’` when the package is not installed.

This is confusing for new users.  Instead, it would be helpful to check for the packages when the tutorial is launched and produce a warning message.

**Comment by nicholasjhorton** [comment]
That's a great suggestion.  We will investigate.

**Comment by rpruim** [comment]
I've decided to solve this by eliminating the hard dependency.   NHANES will only be available in the exercise at the end if you have it installed on your system.

**Comment by rpruim** [comment]
<img width="361" alt="image" src="https://user-images.githubusercontent.com/722231/41877552-b3227896-789f-11e8-98c5-c09d1e8b0f7a.png">
