### ISSUE TITLE
gf_dens() ignores fill parameter

### ISSUE THREAD

**Issue by aloy** [ProjectMOSAIC/ggformula#97]
```
gf_dens(~ Sepal.Length,  color = ~Species, fill = ~Species, data = iris)
``` 
does not utilize the fill parameter, but using `gf_density()` this is possible, is this a bug or a choice? If it's a choice then I think the help file would benefit from having this more explicitly stated (right now you have to parse through the list of parameters). Thanks!

**Comment by rpruim** [comment]
This is a choice.  The difference between the two is the default geom.  `gf_dens()` using a line geom, which has no fill.  `gf_density()` uses the area geom which does.

```r
gf_dens()
## gf_dens() uses 
##     * a formula with shape ~x. 
##     * geom:  line 
##     * stat:  density 
##     * key attributes:  alpha = 0.5, color, group, linetype, size, kernel = "gaussian", n =
##                    512, trim = FALSE
## 
## For more information, try ?gf_dens
gf_density()
## gf_density() uses 
##     * a formula with shape ~x. 
##     * geom:  area 
##     * stat:  density 
##     * key attributes:  alpha = 0.5, color, fill, group, linetype, size, kernel = "gaussian",
##                    n = 512, trim = FALSE
## 
## For more information, try ?gf_density
```

**Comment by aloy** [comment]
Got it, thanks!

**Comment by rpruim** [comment]
I've updated the description.

Formula interface to stat_density()

Description

Computes and draws a kernel density estimate, which is a smoothed version of the histogram and is a useful alternative when the data come from an unerlying smooth distribution. The only difference between gf_dens() and gf_density() is the default geom used to show the density curve: gf_density() uses an area geom (which can be filled). gf_dens() using a line geom (which cannot be filled).

**Comment by aloy** [comment]
That sounds great. Thank you again, Randy!
